on login page ignore security fixes #222
quarkiverse/quarkus-renarde pull request #223
Opened 2024-06-18 02:41 UTC by gbourant

2024-06-18 02:43 UTC, gbourant commented
If this is about to be added i will add some tests and also investigate to remove some code which is used to avoid `redirect loop`

2024-06-18 07:20 UTC, FroMage commented
Can you explain why this is needed and what triggers it? Perhaps with a failing test? I'm surprised I didn't run into this earlier.

2024-06-18 23:09 UTC, gbourant commented
Also my fix is wrong because it makes `SecurityIdentity#isAnonymous` to misbehave in the login page. It always returns false even when the user is already logged in.

2024-06-19 10:16 UTC, FroMage commented
OK. So this happens when trying to access the login page with an invalid cookie. Good point. I've always tested accessing a regular page with an invalid cookie, which would redirect me to the login page after clearing the invalid cookie.

I suppose in this case, it's fine to redirect from the login page to the login page, once, simply because we're clearing the cookie. So it's not a loop. Perhaps add a check in `RenardeSecurity.makeRedirectToLogin` to allow for redirecting to the login page if we have a cookie to clear?

2024-06-19 12:56 UTC, gbourant commented
I've added the check to the `RenardeSecurity.makeRedirectToLogin` method.

2024-06-20 08:21 UTC, FroMage commented
OK that looks good. Could you add your test please? Probably in `JWTTest` in `quarkus-renarde/deployment`.

2024-06-20 11:03 UTC, gbourant commented
I just pushed the test. For some weird reason when i put the test in `JWTTest` class i get the following error, so i added it to the `CustomLoginControllerTest` class if that's ok.

```
[ERROR] Errors: 
[ERROR]   JWTTest » Runtime java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkiverse.renarde.deployment.RenardeProcessor#collectControllers threw an exception: java.lang.IllegalArgumentException: Cannot provide/consume multiple values for class io.quarkiverse.renarde.deployment.LoginPageBuildItem
```

2024-06-25 08:45 UTC, FroMage requested changes

2024-06-25 08:45 UTC, FroMage commented on deployment/src/test/java/io/quarkiverse/renarde/test/CustomLoginControllerTest.java
> +        assertFalse(response.headers().hasHeaderWithName("QuarkusUser"));
This is not testing that it clears the cookie, it checks for headers :)

2024-06-25 08:45 UTC, FroMage commented on deployment/src/test/java/io/quarkiverse/renarde/test/CustomLoginControllerTest.java
> +                .extract().response();
You should also check that you're redirected to `/login`

2024-06-25 10:10 UTC, FroMage approved these changes
Excellent, thanks!

2024-06-25 10:10 UTC, merged